version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - DATABASE_URL=postgres://gograph:gograph@db:5432/gograph?sslmode=disable
      - PORT=8080

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: gograph
      POSTGRES_PASSWORD: gograph
      POSTGRES_DB: gograph
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
