version: '3'

services:
  consul-agent-1:
    container_name: consul-agent-1
    image: consul:1.15
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -node=consul-agent-1 -config-dir=/etc/consul.d -client 0.0.0.0"
    volumes: 
      - ./clients/consul-agent-1:/etc/consul.d

  consul-agent-2:
    container_name: consul-agent-2
    image: consul:1.15
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -node=consul-agent-2 -config-dir=/etc/consul.d -client 0.0.0.0"
    volumes: 
      - ./clients/consul-agent-2:/etc/consul.d
      
  consul-server-1:
    container_name: consul-server-1
    image: consul:1.15
    networks:
      - consul-demo
    command: "agent -server -retry-join consul-server-bootstrap -node=consul-server-1 -client 0.0.0.0"

  consul-server-2:
    container_name: consul-server-2
    image: consul:1.15
    networks:
      - consul-demo
    command: "agent -server -retry-join consul-server-bootstrap -node=consul-server-2 -client 0.0.0.0"

  consul-server-bootstrap:
    container_name: consul-server-bootstrap
    image: consul:1.15
    networks:
      - consul-demo
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -node=consul-server-bootstrap -ui -client 0.0.0.0"

networks:
  consul-demo:
