version: '3'

services:
  consul-agent-1:
    image: consul:1.15
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    # Complete copy of 'consul-agent-1'
    image: consul:1.15
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-3:
    # Complete copy of 'consul-agent-1'
    image: consul:1.15
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-1:
    # Uses only image and networks from 'consul-agent-1'
    # while 'command' is overwritten
    image: consul:1.15
    networks:
      - consul-demo
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    # Complete copy of 'consul-server-1'
    image: consul:1.15
    networks:
      - consul-demo
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-bootstrap:
    # Uses only image and networks from 'consul-agent-1'
    # while 'command' is overwritten and 'ports' are defined
    image: consul:1.15
    networks:
      - consul-demo
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

networks:
  consul-demo:
