version: '3'

services:
  node:
    container_name: node
    build:
      context: node
    networks:
      - desafio-node
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=desafio_node
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-node

  nginx:
    container_name: nginx
    build:
      context: nginx
    networks:
      - desafio-node
    ports:
      - "80:80"
    depends_on:
      - node

networks:
  desafio-node:
    driver: bridge
